//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Booking_HotelsEntities : DbContext
    {
        public Booking_HotelsEntities()
            : base("name=Booking_HotelsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<city> cities { get; set; }
        public virtual DbSet<convenient> convenients { get; set; }
        public virtual DbSet<hotel_type> hotel_type { get; set; }
        public virtual DbSet<price_level> price_level { get; set; }
        public virtual DbSet<room> rooms { get; set; }
        public virtual DbSet<roomDetail> roomDetails { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
